services:
  - type: web
    name: dados-assimilados-bot
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
    autoDeploy: true
